In [1]:
# import library
import numpy as np
import pandas as pd

In [2]:
#function memilih data nilai mahasiswa yg sudah lulus mk Tugas Akhir
def dataMhsLulus(df1,df2):
    #mengambil data nilai mahasiswa yang sudah lulus Tugas Akhir dengan indeksnilai min C
    df_lulus1 = df1[df1['TUGAS AKHIR'] != 0]
    df_lulus1 = df_lulus1[df_lulus1['TUGAS AKHIR'] != 1]
    
    df_lulus2 = df2[df2['TUGAS AKHIR'] != 0]
    df_lulus2 = df_lulus2[df_lulus2['TUGAS AKHIR'] != 1]
    
    #menggabungkan dataset mahasiswa 2016 dan 2017
    df_lulus = pd.concat([df_lulus1,df_lulus2])
    df_lulus = df_lulus.reset_index(drop=True)
    
    return df_lulus

In [3]:
#import data dan memanggil function dataMhsLulus
df1 = pd.read_csv("csv/data_fix1617.csv")
df2 = pd.read_csv("csv/data_fix1718.csv")
df_lulus = dataMhsLulus(df1,df2)
df_lulus

,NIM,TEORI BAHASA DAN AUTOMATA,INTERAKSI MANUSIA KOMPUTER,TATA TULIS ILMIAH DAN TEKNIK PRESENTASI,IMPLEMENTASI DAN PENGUJIAN PERANGKAT LUNAK,ANALISIS KOMPLEKSITAS ALGORITMA,PENULISAN PROPOSAL,PEMODELAN BASIS DATA,FORENSIK KOMPUTER DAN JARINGAN,KALKULUS LANJUT,...,IDENTIFIKASI MASALAH PADA CYBER PHYSICAL SYSTEM,BASIS DATA SPASIAL,PEMBENTUKAN KARAKTER,PERANCANGAN SOLUSI PADA SAINS DATA,IMPLEMENTASI SOLUSI PADA SAINS DATA,PENDIDIKAN AGAMA BUDHA DAN ETIKA,TOPIK PILIHAN PADA SISTEM PERANGKAT LUNAK LANJUT,SISTEM PERANGKAT LUNAK LANJUT II,SISTEM PERANGKAT LUNAK LANJUT III,SISTEM PERANGKAT LUNAK LANJUT I
0,sfff91bad0515fc6,4.0,3.5,4.0,4.0,1.0,4.0,3.5,4.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sfeed7b028f982ab,2.0,3.5,4.0,4.0,4.0,3.5,3.5,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,sfeebfab53074ba2,4.0,3.5,4.0,3.5,2.0,3.0,3.5,0.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,sfe99832907c34ae,3.5,3.0,4.0,2.5,1.0,3.0,3.5,0.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sfe80517b9f97718,4.0,3.5,4.0,3.5,1.0,3.5,2.5,2.5,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,s01d16041c9ff292,3.5,3.5,4.0,3.5,3.5,4.0,3.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1063,s0151d455fde4fe8,2.5,4.0,3.5,4.0,3.0,3.0,3.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1064,s00adab89ebc7558,3.5,2.5,3.5,3.5,3.5,3.5,2.5,0.0,2.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1065,s009e63f36796e76,3.5,3.5,3.5,3.5,2.0,4.0,2.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1066,s0057bf9bca00c25,3.5,3.5,4.0,3.5,3.0,4.0,3.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
#mengambil data dari beberapa kolom mk wajib Intelligent System
df_wajib_is = df_lulus.filter(['LOGIKA MATEMATIKA',
                               'MATEMATIKA DISKRIT',
                               'ALGORITMA PEMROGRAMAN',
                               'ANALISIS KOMPLEKSITAS ALGORITMA',
                               'STRUKTUR DATA',
                               'PENGANTAR KECERDASAN BUATAN',
                               'TEORI BAHASA DAN AUTOMATA',
                               'PEMBELAJARAN MESIN',
                               'PEMROGRAMAN BERORIENTASI OBJEK'])
df_wajib_is

,LOGIKA MATEMATIKA,MATEMATIKA DISKRIT,ALGORITMA PEMROGRAMAN,ANALISIS KOMPLEKSITAS ALGORITMA,STRUKTUR DATA,PENGANTAR KECERDASAN BUATAN,TEORI BAHASA DAN AUTOMATA,PEMBELAJARAN MESIN,PEMROGRAMAN BERORIENTASI OBJEK
0,4.0,1.0,1.0,1.0,4.0,3.5,4.0,4.0,4.0
1,2.0,4.0,2.0,4.0,3.5,3.5,2.0,2.0,3.5
2,4.0,4.0,3.5,2.0,4.0,3.5,4.0,4.0,3.5
3,3.5,3.0,3.5,1.0,3.0,3.5,3.5,0.0,3.0
4,4.0,3.5,2.5,1.0,3.5,3.5,4.0,3.5,2.5
...,...,...,...,...,...,...,...,...,...
1062,4.0,4.0,3.5,3.5,3.0,4.0,3.5,4.0,3.5
1063,4.0,3.5,2.0,3.0,2.5,3.5,2.5,3.5,3.5
1064,2.5,3.0,1.0,3.5,2.5,3.5,3.5,3.5,1.0
1065,3.5,3.0,1.0,2.0,2.0,3.5,3.5,4.0,3.5
1066,3.5,4.0,4.0,3.0,3.0,3.5,3.5,3.5,3.5

In [5]:
#mengambil data dari beberapa kolom mk wajib Cyber Physical System
df_wajib_cps = df_lulus.filter(['SISTEM DIGITAL',
                                'ORGANISASI DAN ARSITEKTUR KOMPUTER',
                                'SISTEM OPERASI',
                                'JARINGAN KOMPUTER',
                                'SISTEM PARALEL DAN TERDISTRIBUSI'])
df_wajib_cps

,SISTEM DIGITAL,ORGANISASI DAN ARSITEKTUR KOMPUTER,SISTEM OPERASI,JARINGAN KOMPUTER,SISTEM PARALEL DAN TERDISTRIBUSI
0,4.0,2.0,4.0,4.0,4.0
1,3.5,3.5,4.0,4.0,2.5
2,3.5,2.0,2.0,3.0,3.5
3,1.0,2.5,4.0,3.5,2.0
4,3.5,2.0,2.0,3.5,3.5
...,...,...,...,...,...
1062,4.0,4.0,4.0,4.0,4.0
1063,4.0,3.5,3.5,4.0,4.0
1064,4.0,2.5,2.0,4.0,4.0
1065,4.0,3.0,3.5,2.0,4.0
1066,2.5,3.5,3.5,3.0,3.5

In [6]:
#mengambil data dari beberapa kolom mk wajib Software Engineering
df_wajib_se = df_lulus.filter(['PEMODELAN BASIS DATA',
                               'RPL: ANALISIS KEBUTUHAN',
                               'SISTEM BASIS DATA',
                               'INTERAKSI MANUSIA KOMPUTER'])
df_wajib_se

,PEMODELAN BASIS DATA,RPL: ANALISIS KEBUTUHAN,SISTEM BASIS DATA,INTERAKSI MANUSIA KOMPUTER
0,3.5,2.0,3.0,3.5
1,3.5,4.0,2.0,3.5
2,3.5,3.5,2.0,3.5
3,3.5,3.5,2.5,3.0
4,2.5,3.5,2.0,3.5
...,...,...,...,...
1062,3.0,3.5,4.0,3.5
1063,3.0,4.0,2.5,4.0
1064,2.5,3.5,3.0,2.5
1065,2.0,3.5,3.0,3.5
1066,3.0,3.5,3.0,3.5

In [7]:
#mengambil data dari beberapa kolom mk wajib Data Science
df_wajib_ds = df_lulus.filter(['KALKULUS',
                               'STATISTIKA',
                               'KALKULUS LANJUT',
                               'MATRIKS DAN RUANG VEKTOR',
                               'TEORI PELUANG'])
df_wajib_ds

,KALKULUS,STATISTIKA,KALKULUS LANJUT,MATRIKS DAN RUANG VEKTOR,TEORI PELUANG
0,2.5,4.0,1.0,2.0,1.0
1,3.0,3.5,4.0,2.0,2.5
2,4.0,4.0,4.0,4.0,3.0
3,3.0,3.5,3.0,3.0,3.0
4,3.5,4.0,4.0,2.5,2.0
...,...,...,...,...,...
1062,4.0,4.0,4.0,3.5,4.0
1063,4.0,4.0,4.0,4.0,4.0
1064,2.5,4.0,2.5,2.5,3.0
1065,2.5,4.0,3.0,2.5,2.0
1066,4.0,4.0,4.0,3.0,3.5

In [8]:
#membuat dataset baru yg hanya berisikan kolom mata kuliah dasar, wajib icm, wajib side, dan wajib tele
df = df_lulus
df_lulus = pd.concat([df_wajib_is, df_wajib_cps, df_wajib_se, df_wajib_ds], axis=1)

In [9]:
#setiap mk wajib IS, CPS, SE dan DS dikali bobot sksnya masing - masing
df_wajib_is['LOGIKA MATEMATIKA'] = df_wajib_is['LOGIKA MATEMATIKA'] * 3
df_wajib_is['MATEMATIKA DISKRIT'] = df_wajib_is['MATEMATIKA DISKRIT'] * 3
df_wajib_is['ALGORITMA PEMROGRAMAN'] = df_wajib_is['ALGORITMA PEMROGRAMAN'] * 4
df_wajib_is['ANALISIS KOMPLEKSITAS ALGORITMA'] = df_wajib_is['ANALISIS KOMPLEKSITAS ALGORITMA'] * 2
df_wajib_is['STRUKTUR DATA'] = df_wajib_is['STRUKTUR DATA'] * 4
df_wajib_is['PENGANTAR KECERDASAN BUATAN'] = df_wajib_is['PENGANTAR KECERDASAN BUATAN'] * 3
df_wajib_is['TEORI BAHASA DAN AUTOMATA'] = df_wajib_is['TEORI BAHASA DAN AUTOMATA'] * 3
df_wajib_is['PEMBELAJARAN MESIN'] = df_wajib_is['PEMBELAJARAN MESIN'] * 3
df_wajib_is['PEMROGRAMAN BERORIENTASI OBJEK'] = df_wajib_is['PEMROGRAMAN BERORIENTASI OBJEK'] * 4

df_wajib_cps['SISTEM DIGITAL'] = df_wajib_cps['SISTEM DIGITAL'] * 3
df_wajib_cps['ORGANISASI DAN ARSITEKTUR KOMPUTER'] = df_wajib_cps['ORGANISASI DAN ARSITEKTUR KOMPUTER'] * 3
df_wajib_cps['SISTEM OPERASI'] = df_wajib_cps['SISTEM OPERASI'] * 3
df_wajib_cps['JARINGAN KOMPUTER'] = df_wajib_cps['JARINGAN KOMPUTER'] * 4
df_wajib_cps['SISTEM PARALEL DAN TERDISTRIBUSI'] = df_wajib_cps['SISTEM PARALEL DAN TERDISTRIBUSI'] * 4

df_wajib_se['PEMODELAN BASIS DATA'] = df_wajib_se['PEMODELAN BASIS DATA'] * 3
df_wajib_se['RPL: ANALISIS KEBUTUHAN'] = df_wajib_se['RPL: ANALISIS KEBUTUHAN'] * 2
df_wajib_se['SISTEM BASIS DATA'] = df_wajib_se['SISTEM BASIS DATA'] * 3
df_wajib_se['INTERAKSI MANUSIA KOMPUTER'] = df_wajib_se['INTERAKSI MANUSIA KOMPUTER'] * 3

df_wajib_ds['KALKULUS'] = df_wajib_ds['KALKULUS'] * 3
df_wajib_ds['STATISTIKA'] = df_wajib_ds['STATISTIKA'] * 2
df_wajib_ds['KALKULUS LANJUT'] = df_wajib_ds['KALKULUS LANJUT'] * 3
df_wajib_ds['MATRIKS DAN RUANG VEKTOR'] = df_wajib_ds['MATRIKS DAN RUANG VEKTOR'] * 3
df_wajib_ds['TEORI PELUANG'] = df_wajib_ds['TEORI PELUANG'] * 3

In [10]:
#penghitungan nilai akhir setiap KK (((MK * SKS) + MK lainnya pada kk yang sama) / total bobot sks)
nilai_tiap_kk = pd.DataFrame(columns = ['IS', 'CPS', 'SE', 'DS'])

for index, row in df_wajib_is.iterrows():
    hasil = 0
    nilai_tiap_kk.loc[index] = np.nan
    for column in df_wajib_is:
        hasil_convert = df_wajib_is.loc[index, column]
        hasil = hasil + hasil_convert
    hasil = hasil / 29
    nilai_tiap_kk['IS'][index] = hasil
    
for index, row in df_wajib_cps.iterrows():
    hasil = 0
    for column in df_wajib_cps:
        hasil_convert = df_wajib_cps.loc[index, column]
        hasil = hasil + hasil_convert
    hasil = hasil / 17
    nilai_tiap_kk['CPS'][index] = hasil
    
for index, row in df_wajib_se.iterrows():
    hasil = 0
    for column in df_wajib_se:
        hasil_convert = df_wajib_se.loc[index, column]
        hasil = hasil + hasil_convert
    hasil = hasil / 11
    nilai_tiap_kk['SE'][index] = hasil

for index, row in df_wajib_ds.iterrows():
    hasil = 0
    for column in df_wajib_ds:
        hasil_convert = df_wajib_ds.loc[index, column]
        hasil = hasil + hasil_convert
    hasil = hasil / 14
    nilai_tiap_kk['DS'][index] = hasil

In [11]:
#menyimpan data nilai_tiap_kk ke dalam file total_nilai_tiap_kk.csv
nilai_tiap_kk.to_csv('csv/total_nilai_tiap_kk.csv', index = False)
nilai_tiap_kk

            IS       CPS        SE        DS
0     3.017241  3.647059  3.090909  1.964286
1     2.913793  3.470588  3.181818  2.964286
2     3.672414  2.852941  3.090909  3.785714
3     2.775862  2.617647  3.090909  3.071429
4     3.155172  2.970588  2.818182  3.142857
...        ...       ...       ...       ...
1062  3.637931       4.0       3.5  3.892857
1063  3.068966  3.823529  3.318182       4.0
1064  2.517241  3.382353  2.818182  2.821429
1065  2.844828  3.264706  2.954545  2.714286
1066  3.517241  3.205882  3.227273  3.678571

[1067 rows x 4 columns]

In [12]:
#membuat kolom Kelompok Keahlian pada dataset nilai_tiap_kk
nilai_tiap_kk['KK'] = np.nan

#menentukan Kelompok Keahlian berdasarkan nilai tertinggi pada dataframe nilai_tiap_kk
#dan melakukan penandaan jika terdapat data yang bersifat ambigu
for index, row in nilai_tiap_kk.iterrows():
    if nilai_tiap_kk['IS'][index] > nilai_tiap_kk['CPS'][index] and nilai_tiap_kk['IS'][index] > nilai_tiap_kk['SE'][index] and nilai_tiap_kk['IS'][index] > nilai_tiap_kk['DS'][index]:
        KK = 0
    elif nilai_tiap_kk['CPS'][index] > nilai_tiap_kk['IS'][index] and nilai_tiap_kk['CPS'][index] > nilai_tiap_kk['SE'][index] and nilai_tiap_kk['CPS'][index] > nilai_tiap_kk['DS'][index]:
        KK = 1
    elif nilai_tiap_kk['SE'][index] > nilai_tiap_kk['IS'][index] and nilai_tiap_kk['SE'][index] > nilai_tiap_kk['CPS'][index] and nilai_tiap_kk['SE'][index] > nilai_tiap_kk['DS'][index]:
        KK = 2
    elif nilai_tiap_kk['DS'][index] > nilai_tiap_kk['IS'][index] and nilai_tiap_kk['DS'][index] > nilai_tiap_kk['CPS'][index] and nilai_tiap_kk['DS'][index] > nilai_tiap_kk['SE'][index]:
        KK = 3

    nilai_tiap_kk.loc[index, 'KK'] = KK
    KK = 4 #jika terdapat data yg bersifat ambigu KK = 4

In [13]:
#menggabungkan dataset df_lulus dengan dataset df bagian kolom KK saja
df_lulus = pd.concat([df_lulus, nilai_tiap_kk['KK']], axis=1)
df_lulus

,LOGIKA MATEMATIKA,MATEMATIKA DISKRIT,ALGORITMA PEMROGRAMAN,ANALISIS KOMPLEKSITAS ALGORITMA,STRUKTUR DATA,PENGANTAR KECERDASAN BUATAN,TEORI BAHASA DAN AUTOMATA,PEMBELAJARAN MESIN,PEMROGRAMAN BERORIENTASI OBJEK,SISTEM DIGITAL,...,PEMODELAN BASIS DATA,RPL: ANALISIS KEBUTUHAN,SISTEM BASIS DATA,INTERAKSI MANUSIA KOMPUTER,KALKULUS,STATISTIKA,KALKULUS LANJUT,MATRIKS DAN RUANG VEKTOR,TEORI PELUANG,KK
0,4.0,1.0,1.0,1.0,4.0,3.5,4.0,4.0,4.0,4.0,...,3.5,2.0,3.0,3.5,2.5,4.0,1.0,2.0,1.0,1.0
1,2.0,4.0,2.0,4.0,3.5,3.5,2.0,2.0,3.5,3.5,...,3.5,4.0,2.0,3.5,3.0,3.5,4.0,2.0,2.5,1.0
2,4.0,4.0,3.5,2.0,4.0,3.5,4.0,4.0,3.5,3.5,...,3.5,3.5,2.0,3.5,4.0,4.0,4.0,4.0,3.0,3.0
3,3.5,3.0,3.5,1.0,3.0,3.5,3.5,0.0,3.0,1.0,...,3.5,3.5,2.5,3.0,3.0,3.5,3.0,3.0,3.0,2.0
4,4.0,3.5,2.5,1.0,3.5,3.5,4.0,3.5,2.5,3.5,...,2.5,3.5,2.0,3.5,3.5,4.0,4.0,2.5,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,4.0,4.0,3.5,3.5,3.0,4.0,3.5,4.0,3.5,4.0,...,3.0,3.5,4.0,3.5,4.0,4.0,4.0,3.5,4.0,1.0
1063,4.0,3.5,2.0,3.0,2.5,3.5,2.5,3.5,3.5,4.0,...,3.0,4.0,2.5,4.0,4.0,4.0,4.0,4.0,4.0,3.0
1064,2.5,3.0,1.0,3.5,2.5,3.5,3.5,3.5,1.0,4.0,...,2.5,3.5,3.0,2.5,2.5,4.0,2.5,2.5,3.0,1.0
1065,3.5,3.0,1.0,2.0,2.0,3.5,3.5,4.0,3.5,4.0,...,2.0,3.5,3.0,3.5,2.5,4.0,3.0,2.5,2.0,1.0
1066,3.5,4.0,4.0,3.0,3.0,3.5,3.5,3.5,3.5,2.5,...,3.0,3.5,3.0,3.5,4.0,4.0,4.0,3.0,3.5,3.0

In [14]:
#melakukan pengecekkan banyaknya mahasiswa pada setiap Kelompok Keahlian (IS, CPS, SE, DS)
print('Total Mahasiswa KK IS  = ', len(df_lulus[df_lulus['KK'] == 0]))
print('Total Mahasiswa KK CPS = ', len(df_lulus[df_lulus['KK'] == 1]))
print('Total Mahasiswa KK SE = ', len(df_lulus[df_lulus['KK'] == 2]))
print('Total Mahasiswa KK DS = ', len(df_lulus[df_lulus['KK'] == 3]))

Total Mahasiswa KK IS  =  139
Total Mahasiswa KK CPS =  487
Total Mahasiswa KK SE =  139
Total Mahasiswa KK DS =  274

In [15]:
#mengisi nilai null menjadi 4 sebagai penanda bahwa pada data tsb ambigu dan memasukkannya ke dalam dataset ambigu
df_ambigu = pd.DataFrame(columns=df_lulus.columns)
nilai_tiap_kk_ambigu = pd.DataFrame(columns=nilai_tiap_kk.columns) 

#memindahkan data yang bersifat ambigu ke dalam df_ambigu dan melakukan drop data yang bersifat ambigu pada dataset df_lulus
for index, row in nilai_tiap_kk.iterrows():
    if nilai_tiap_kk['KK'][index] == 4:
        df_ambigu = df_ambigu.append(df_lulus.loc[index])
        df_lulus = df_lulus.drop([index])
        
        nilai_tiap_kk_ambigu = nilai_tiap_kk_ambigu.append(nilai_tiap_kk.loc[index])
        
df_ambigu = df_ambigu.drop(['KK'], axis = 1)
df_ambigu = df_ambigu.reset_index(drop=True)
nilai_tiap_kk_ambigu = nilai_tiap_kk_ambigu.reset_index(drop=True)
df_lulus = df_lulus.reset_index(drop=True)
df_lulus

,LOGIKA MATEMATIKA,MATEMATIKA DISKRIT,ALGORITMA PEMROGRAMAN,ANALISIS KOMPLEKSITAS ALGORITMA,STRUKTUR DATA,PENGANTAR KECERDASAN BUATAN,TEORI BAHASA DAN AUTOMATA,PEMBELAJARAN MESIN,PEMROGRAMAN BERORIENTASI OBJEK,SISTEM DIGITAL,...,PEMODELAN BASIS DATA,RPL: ANALISIS KEBUTUHAN,SISTEM BASIS DATA,INTERAKSI MANUSIA KOMPUTER,KALKULUS,STATISTIKA,KALKULUS LANJUT,MATRIKS DAN RUANG VEKTOR,TEORI PELUANG,KK
0,4.0,1.0,1.0,1.0,4.0,3.5,4.0,4.0,4.0,4.0,...,3.5,2.0,3.0,3.5,2.5,4.0,1.0,2.0,1.0,1.0
1,2.0,4.0,2.0,4.0,3.5,3.5,2.0,2.0,3.5,3.5,...,3.5,4.0,2.0,3.5,3.0,3.5,4.0,2.0,2.5,1.0
2,4.0,4.0,3.5,2.0,4.0,3.5,4.0,4.0,3.5,3.5,...,3.5,3.5,2.0,3.5,4.0,4.0,4.0,4.0,3.0,3.0
3,3.5,3.0,3.5,1.0,3.0,3.5,3.5,0.0,3.0,1.0,...,3.5,3.5,2.5,3.0,3.0,3.5,3.0,3.0,3.0,2.0
4,4.0,3.5,2.5,1.0,3.5,3.5,4.0,3.5,2.5,3.5,...,2.5,3.5,2.0,3.5,3.5,4.0,4.0,2.5,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,4.0,4.0,3.5,3.5,3.0,4.0,3.5,4.0,3.5,4.0,...,3.0,3.5,4.0,3.5,4.0,4.0,4.0,3.5,4.0,1.0
1035,4.0,3.5,2.0,3.0,2.5,3.5,2.5,3.5,3.5,4.0,...,3.0,4.0,2.5,4.0,4.0,4.0,4.0,4.0,4.0,3.0
1036,2.5,3.0,1.0,3.5,2.5,3.5,3.5,3.5,1.0,4.0,...,2.5,3.5,3.0,2.5,2.5,4.0,2.5,2.5,3.0,1.0
1037,3.5,3.0,1.0,2.0,2.0,3.5,3.5,4.0,3.5,4.0,...,2.0,3.5,3.0,3.5,2.5,4.0,3.0,2.5,2.0,1.0
1038,3.5,4.0,4.0,3.0,3.0,3.5,3.5,3.5,3.5,2.5,...,3.0,3.5,3.0,3.5,4.0,4.0,4.0,3.0,3.5,3.0

In [16]:
#melakukan pengecekkan banyaknya mahasiswa pada setiap Kelompok Keahlian (IS, CPS, SE, DS) setelah drop data ambigu
print('Total Mahasiswa KK IS  = ', len(df_lulus[df_lulus['KK'] == 0]))
print('Total Mahasiswa KK CPS = ', len(df_lulus[df_lulus['KK'] == 1]))
print('Total Mahasiswa KK SE = ', len(df_lulus[df_lulus['KK'] == 2]))
print('Total Mahasiswa KK DS = ', len(df_lulus[df_lulus['KK'] == 3]))

Total Mahasiswa KK IS  =  139
Total Mahasiswa KK CPS =  487
Total Mahasiswa KK SE =  139
Total Mahasiswa KK DS =  274

In [17]:
nilai_tiap_kk_ambigu

          IS       CPS        SE        DS   KK
0   3.931034  4.000000  4.000000  3.892857  4.0
1   4.000000  4.000000  3.863636  4.000000  4.0
2   3.500000  4.000000  3.727273  4.000000  4.0
3   3.862069  4.000000  3.863636  4.000000  4.0
4   4.000000  4.000000  3.863636  3.678571  4.0
5   4.000000  3.911765  3.363636  4.000000  4.0
6   3.862069  4.000000  3.909091  4.000000  4.0
7   3.896552  4.000000  3.500000  4.000000  4.0
8   4.000000  3.647059  4.000000  4.000000  4.0
9   4.000000  4.000000  3.772727  4.000000  4.0
10  2.086207  2.500000  1.181818  2.500000  4.0
11  3.931034  4.000000  3.454545  4.000000  4.0
12  3.948276  4.000000  4.000000  3.785714  4.0
13  4.000000  4.000000  3.454545  3.892857  4.0
14  3.931034  4.000000  3.545455  4.000000  4.0
15  4.000000  3.911765  3.863636  4.000000  4.0
16  3.689655  4.000000  4.000000  3.892857  4.0
17  3.724138  3.823529  4.000000  4.000000  4.0
18  3.586207  4.000000  4.000000  3.571429  4.0
19  2.310345  3.000000  2.272727  3.000000  4.0
20  4.000000  3.823529  3.909091  4.000000  4.0
21  3.862069  4.000000  3.909091  4.000000  4.0
22  3.948276  3.764706  4.000000  4.000000  4.0
23  4.000000  3.911765  3.863636  4.000000  4.0
24  4.000000  3.911765  3.727273  4.000000  4.0
25  3.500000  3.441176  3.500000  3.142857  4.0
26  2.500000  3.500000  2.954545  3.500000  4.0
27  4.000000  3.823529  4.000000  4.000000  4.0

In [18]:
#drop data yg memiliki nilai 0 pada setiap prasyarat KK (dianggap sebagai Fake Data)
for index, row in df_lulus.iterrows():
    for column in df_wajib_is:
        df_lulus = df_lulus[df_lulus[column] != 0]
    for column in df_wajib_cps:
        df_lulus = df_lulus[df_lulus[column] != 0]
    for column in df_wajib_se:
        df_lulus = df_lulus[df_lulus[column] != 0]
    for column in df_wajib_ds:
        df_lulus = df_lulus[df_lulus[column] != 0]
df_lulus = df_lulus.reset_index(drop=True)
df_lulus

,LOGIKA MATEMATIKA,MATEMATIKA DISKRIT,ALGORITMA PEMROGRAMAN,ANALISIS KOMPLEKSITAS ALGORITMA,STRUKTUR DATA,PENGANTAR KECERDASAN BUATAN,TEORI BAHASA DAN AUTOMATA,PEMBELAJARAN MESIN,PEMROGRAMAN BERORIENTASI OBJEK,SISTEM DIGITAL,...,PEMODELAN BASIS DATA,RPL: ANALISIS KEBUTUHAN,SISTEM BASIS DATA,INTERAKSI MANUSIA KOMPUTER,KALKULUS,STATISTIKA,KALKULUS LANJUT,MATRIKS DAN RUANG VEKTOR,TEORI PELUANG,KK
0,4.0,1.0,1.0,1.0,4.0,3.5,4.0,4.0,4.0,4.0,...,3.5,2.0,3.0,3.5,2.5,4.0,1.0,2.0,1.0,1.0
1,2.0,4.0,2.0,4.0,3.5,3.5,2.0,2.0,3.5,3.5,...,3.5,4.0,2.0,3.5,3.0,3.5,4.0,2.0,2.5,1.0
2,4.0,4.0,3.5,2.0,4.0,3.5,4.0,4.0,3.5,3.5,...,3.5,3.5,2.0,3.5,4.0,4.0,4.0,4.0,3.0,3.0
3,4.0,3.5,2.5,1.0,3.5,3.5,4.0,3.5,2.5,3.5,...,2.5,3.5,2.0,3.5,3.5,4.0,4.0,2.5,2.0,0.0
4,4.0,4.0,3.0,2.5,3.5,4.0,3.5,4.0,2.5,3.5,...,3.5,4.0,2.0,4.0,3.5,4.0,3.5,3.5,3.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976,4.0,4.0,3.5,3.5,3.0,4.0,3.5,4.0,3.5,4.0,...,3.0,3.5,4.0,3.5,4.0,4.0,4.0,3.5,4.0,1.0
977,4.0,3.5,2.0,3.0,2.5,3.5,2.5,3.5,3.5,4.0,...,3.0,4.0,2.5,4.0,4.0,4.0,4.0,4.0,4.0,3.0
978,2.5,3.0,1.0,3.5,2.5,3.5,3.5,3.5,1.0,4.0,...,2.5,3.5,3.0,2.5,2.5,4.0,2.5,2.5,3.0,1.0
979,3.5,3.0,1.0,2.0,2.0,3.5,3.5,4.0,3.5,4.0,...,2.0,3.5,3.0,3.5,2.5,4.0,3.0,2.5,2.0,1.0
980,3.5,4.0,4.0,3.0,3.0,3.5,3.5,3.5,3.5,2.5,...,3.0,3.5,3.0,3.5,4.0,4.0,4.0,3.0,3.5,3.0

In [19]:
#menyimpan dataset training dan dataset ambigu
df_lulus.to_csv('csv/data_train1617.csv', index = False)
df_ambigu.to_csv('csv/data_ambigu.csv', index = False)

In [20]:
#melakukan pengecekkan banyaknya mahasiswa pada setiap Kelompok Keahlian (IS, CPS, SE, DS) 
print('Total Mahasiswa KK IS  = ', len(df_lulus[df_lulus['KK'] == 0]))
print('Total Mahasiswa KK CPS = ', len(df_lulus[df_lulus['KK'] == 1]))
print('Total Mahasiswa KK SE = ', len(df_lulus[df_lulus['KK'] == 2]))
print('Total Mahasiswa KK DS = ', len(df_lulus[df_lulus['KK'] == 3]))

Total Mahasiswa KK IS  =  138
Total Mahasiswa KK CPS =  459
Total Mahasiswa KK SE =  125
Total Mahasiswa KK DS =  259

In [21]:
#testing
#membuat data training dengan ketentuan 125 data setiap KKnya (undersampling)
IS = 0
CPS = 0
SE = 0
DS = 0

df_new_train = pd.DataFrame(columns=df_lulus.columns)

for index, row in df_lulus.iterrows():
    if df_lulus['KK'][index] == 0 and IS != 125:
        df_new_train = df_new_train.append(df_lulus.loc[index])
        IS = IS + 1
    elif df_lulus['KK'][index] == 1 and CPS != 125:
        df_new_train = df_new_train.append(df_lulus.loc[index])
        CPS = CPS + 1
    elif df_lulus['KK'][index] == 2 and SE != 125:
        df_new_train = df_new_train.append(df_lulus.loc[index])
        SE = SE + 1
    elif df_lulus['KK'][index] == 3 and DS != 125:
        df_new_train = df_new_train.append(df_lulus.loc[index])
        DS = DS + 1
        
df_new_train = df_new_train.reset_index(drop=True)

In [22]:
df_new_train.to_csv('csv/data_train1617_undersampling.csv', index = False)
df_new_train

,LOGIKA MATEMATIKA,MATEMATIKA DISKRIT,ALGORITMA PEMROGRAMAN,ANALISIS KOMPLEKSITAS ALGORITMA,STRUKTUR DATA,PENGANTAR KECERDASAN BUATAN,TEORI BAHASA DAN AUTOMATA,PEMBELAJARAN MESIN,PEMROGRAMAN BERORIENTASI OBJEK,SISTEM DIGITAL,...,PEMODELAN BASIS DATA,RPL: ANALISIS KEBUTUHAN,SISTEM BASIS DATA,INTERAKSI MANUSIA KOMPUTER,KALKULUS,STATISTIKA,KALKULUS LANJUT,MATRIKS DAN RUANG VEKTOR,TEORI PELUANG,KK
0,4.0,1.0,1.0,1.0,4.0,3.5,4.0,4.0,4.0,4.0,...,3.5,2.0,3.0,3.5,2.5,4.0,1.0,2.0,1.0,1.0
1,2.0,4.0,2.0,4.0,3.5,3.5,2.0,2.0,3.5,3.5,...,3.5,4.0,2.0,3.5,3.0,3.5,4.0,2.0,2.5,1.0
2,4.0,4.0,3.5,2.0,4.0,3.5,4.0,4.0,3.5,3.5,...,3.5,3.5,2.0,3.5,4.0,4.0,4.0,4.0,3.0,3.0
3,4.0,3.5,2.5,1.0,3.5,3.5,4.0,3.5,2.5,3.5,...,2.5,3.5,2.0,3.5,3.5,4.0,4.0,2.5,2.0,0.0
4,4.0,4.0,3.0,2.5,3.5,4.0,3.5,4.0,2.5,3.5,...,3.5,4.0,2.0,4.0,3.5,4.0,3.5,3.5,3.5,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,3.5,4.0,2.0,3.5,2.0,4.0,3.5,3.5,3.0,4.0,...,4.0,3.0,3.0,3.5,3.5,4.0,2.0,3.0,3.0,2.0
496,3.0,3.5,3.5,2.5,3.5,4.0,3.0,4.0,4.0,3.0,...,3.5,3.5,3.5,4.0,2.0,4.0,2.0,3.0,3.0,2.0
497,4.0,4.0,3.5,2.0,4.0,3.5,4.0,4.0,3.0,4.0,...,4.0,3.5,3.5,4.0,4.0,3.5,3.5,4.0,3.5,2.0
498,4.0,3.5,3.5,2.0,4.0,2.0,4.0,4.0,4.0,3.5,...,4.0,3.5,3.0,4.0,3.5,4.0,3.0,3.0,3.0,2.0
499,2.0,2.5,2.5,2.5,3.0,4.0,2.0,4.0,2.0,1.0,...,3.0,4.0,3.0,3.0,2.0,4.0,1.0,2.0,2.5,2.0

In [23]:
import pandas_profiling
from pandas_profiling import ProfileReport

#eksplorasi Data Menggunakan Pandas Profiling Report

pandas_report = df_lulus.profile_report(sort='None', html={'style':{'full_width': True}})
pandas_report

Tab(children=(HTML(value='<div id="overview-content" class="row variable spacing">\n    <div class="row">\n   …